from typing import Protocol, List, Dict, Optional, Callable


class GameBot(Protocol):
    # 生命周期
    def bind(self) -> bool: ...

    def refresh(self) -> bool: ...

    def giveup(self, delay_sec: float = 0.1) -> bool: ...

    def start_game(self, delay_sec: float = 0.1) -> bool: ...

    def op_tsumo(self, delay_sec: float = 0.3) -> bool: ...

    def op_skip_replace(self, delay_sec: float = 0.3) -> bool: ...

    def op_replace(self, tile_id: int, delay_sec: float = 0.3) -> bool: ...

    def discard_by_tile_id(
            self,
            tile_id: int,
            allow_tsumogiri: bool = True
    ) -> bool: ...

    def select_free_effect(self, selected_id: int, delay_sec: float = 0.3) -> bool: ...

    def select_reward_effect(self, selected_id: int, delay_sec: float = 0.3) -> bool: ...

    def select_effect(self, selected_id: int, delay_sec: float = 0.3) -> bool: ...

    def buy_pack(self, good_id: int, delay_sec: float = 0.3) -> bool: ...

    def refresh_shop(self, delay_sec: float = 0.3): ...

    def sell_effect(self, uid: int, delay_sec: float = 0.3): ...

    def end_shopping(self, delay_sec: float = 0.3): ...

    def next_level(self, delay_sec: float = 0.3): ...
