
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async backendSnapshot() : Promise<BackendSnapshot> {
    return await TAURI_INVOKE("backend_snapshot");
},
async backendCheckVersion(version: string) : Promise<VersionMismatch | null> {
    return await TAURI_INVOKE("backend_check_version", { version });
},
async backendGetPacketPipeline() : Promise<PipelineConfig> {
    return await TAURI_INVOKE("backend_get_packet_pipeline");
},
async backendSetPacketPipeline(config: PipelineConfig) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_set_packet_pipeline", { config });
},
async backendGetPacketLog() : Promise<PacketLogSnapshot> {
    return await TAURI_INVOKE("backend_get_packet_log");
},
async backendReplayPacket(method: string, payload: Partial<{ [key in string]: JsonValue }>) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_replay_packet", { method, payload });
},
async backendUpdateConfig(config: Partial<{ [key in string]: Partial<{ [key in string]: JsonValue }> }>) : Promise<null> {
    return await TAURI_INVOKE("backend_update_config", { config });
},
async backendSetLocale(locale: string) : Promise<void> {
    await TAURI_INVOKE("backend_set_locale", { locale });
},
async backendDumpFlows() : Promise<FlowDumpResult> {
    return await TAURI_INVOKE("backend_dump_flows");
},
async backendFetchActivity(activityId: number) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_fetch_activity", { activityId });
},
async backendDiscardTile(tileId: number) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_discard_tile", { tileId });
},
async backendUpgradeShopBuff(activityId: number, id: number) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_upgrade_shop_buff", { activityId, id });
},
async backendAmuletAction(request: AmuletActionRequest) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_amulet_action", { request });
},
async backendStartTsumoLoop(intervalMs: number, resetCount: boolean) : Promise<TsumoLoopStatus> {
    return await TAURI_INVOKE("backend_start_tsumo_loop", { intervalMs, resetCount });
},
async backendStopTsumoLoop() : Promise<TsumoLoopStatus> {
    return await TAURI_INVOKE("backend_stop_tsumo_loop");
},
async backendAutorun(action: AutorunAction, force: boolean, mode: string | null) : Promise<CommandResult> {
    return await TAURI_INVOKE("backend_autorun", { action, force, mode });
},
async backendResolveConfirmation(id: string, ok: boolean) : Promise<void> {
    await TAURI_INVOKE("backend_resolve_confirmation", { id, ok });
},
async backendSwitch(request: SwitchRequest) : Promise<null> {
    return await TAURI_INVOKE("backend_switch", { request });
},
async backendOpenConfigDir() : Promise<null> {
    return await TAURI_INVOKE("backend_open_config_dir");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AmuletAction = "buy_pack" | "refresh_shop" | "skip" | "select_candidate" | "sell_effect" | "sort_effect" | "sell_recent"
export type AmuletActionRequest = { action: AmuletAction; goodId?: number | null; selectedIndex?: number | null; uid?: number | null; sortedUid?: number[] | null; rawId?: number | null }
export type AutoRunnerConfig = { end_count: number; targets: JsonValue[]; cutoff_level: number | null; op_interval_ms: number | null; need_pionner_badge_count: number | null; record_detailed_operations: boolean | null; email_notify: EmailNotifyConfig | null }
export type AutoRunnerStatus = { mode: string | null; running: boolean; runs: number; elapsed_ms: number; best_achieved_count: number; current_achieved_count: number | null; current_step: string | null; last_error: string | null; started_at: number | null; game_ready: boolean | null; has_live_game: boolean | null; game_ready_reason: string | null; game_ready_code: string | null; probe_fail_count: number | null; preferred_flow_ready: boolean | null; preferred_flow_peer: string | null; remake_records: JsonValue[] | null; best_remake_record: JsonValue | null; record_detailed_operations: boolean | null; operation_records: JsonValue[] | null; operation_count_by_run: Partial<{ [key in string]: number }> | null }
export type AutorunAction = "start" | "stop" | "step" | "probe" | "notify_test_email" | "set_mode"
export type BackendSnapshot = { version: string; backendLogs: LogEntry[]; packetPipeline: PipelineConfig; fuseConfig: FuseConfig; autorunConfig: AutoRunnerConfig; registry: RegistryPayload; config: Partial<{ [key in string]: Partial<{ [key in string]: JsonValue }> }>; gameState: GameStateData; autorunStatus: AutoRunnerStatus; tsumoLoopStatus: TsumoLoopStatus; packetLog: PacketLogSnapshot }
export type CommandResult = { ok: boolean; reason?: string | null; error?: string | null; requires_confirmation?: boolean | null; reason_key?: string | null; reason_values?: Partial<{ [key in string]: JsonValue }> | null; action?: string | null; stage?: number | null; cost?: number | null; coin?: number | null; msg_id?: number | null; response?: JsonValue | null }
export type Direction = "outbound" | "inbound"
export type EmailNotifyConfig = { enabled: boolean; host: string; port: number; ssl: boolean; from: string; pass: string; to: string }
export type FlowDumpItem = { id: number; peer_key: string; client: string; server: string; websocket: boolean; toServer: boolean; toClient: boolean; is_preferred: boolean; activity: number; business_activity: number }
export type FlowDumpResult = { ok: boolean; count: number; flows: FlowDumpItem[] }
export type FuseConfig = { guard_skip_contains: FuseGuardItems; enable_skip_guard: boolean | null; enable_shop_force_pick: boolean | null; enable_ting_ready_skip_guard: boolean | null; enable_prestart_kavi_guard: boolean | null; conduction_min_count: number | null; enable_anti_steal_eat: boolean | null; enable_missing_hand_tile_guard: boolean | null; enable_kavi_plus_buffer_guard: boolean | null; enable_hanabi_win_guard: boolean | null; enable_exit_coin_guard: boolean | null; enable_exit_life_guard: boolean | null }
export type FuseGuardItems = { amulets: number[]; badges: number[] }
export type GameStateData = { stage: number; coin: string; point: string | null; target_point: string | null; level: number | null; node: number | null; map_nodes: JsonValue[] | null; deck_map: Partial<{ [key in string]: string }>; hand_tiles: number[]; dora_tiles: number[]; tian_dora_tiles: JsonValue[] | null; ming: JsonValue[] | null; replacement_tiles: number[]; wall_tiles: number[]; ended: boolean | null; desktop_remain: number; locked_tiles: number[]; switch_used_tiles: number[]; effect_list: JsonValue[] | null; goods: JsonValue[] | null; refresh_price: number | null; candidate_effect_list: JsonValue[] | null; boss_buff: number[] | null; shop_buff_list: Partial<{ [key in string]: number }> | null; change_tile_count: number | null; total_change_tile_count: number | null; max_effect_volume: number | null; tile_score_map: Partial<{ [key in string]: string }> | null; fan_value_map: Partial<{ [key in string]: string }> | null; character_id: JsonValue | null; hp: JsonValue | null; max_hp: JsonValue | null; update_reason: string[] | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LogEntry = { ts_ms: number; level: string; target: string; file: string | null; line: number | null; message: string; fields: Partial<{ [key in string]: JsonValue }> }
export type ModuleConfig = { id: string; enabled: boolean; options?: Partial<{ [key in string]: JsonValue }> }
export type PacketLogItem = { direction: Direction; type: string; method: string; id: number | null; data: JsonValue; ts_ms: number }
export type PacketLogSnapshot = { packets: PacketLogItem[] }
export type PipelineConfig = { schema: number; modules: ModuleConfig[] }
export type RegistryAmulet = { id: number; icon_id: number; name: string; rarity: string }
export type RegistryBadge = { id: number; icon_id: number; name: string; rarity: string }
export type RegistryPayload = { amulets: RegistryAmulet[]; badges: RegistryBadge[] }
export type SwitchAction = "start" | "start_debug" | "list_quads" | "validate_manual_debug" | "execute_plan" | "execute_full_plan" | "stop"
export type SwitchRequest = { action: SwitchAction; options?: Partial<{ [key in string]: JsonValue }> | null; snapshot?: JsonValue | null; quadGroups?: JsonValue | null; structureGroups?: JsonValue | null; notify?: boolean | null }
export type TsumoLoopStatus = { running: boolean; lastReason: string; winCount: number }
export type VersionMismatch = { frontendVersion: string; backendVersion: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
