import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {build} = createRequire(require.resolve('vite'))('esbuild');
const output = await build({entryPoints:['src/lib/scoreEngine.ts'], bundle:true, write:false, platform:'node', format:'cjs'});
const module = {exports:{}};
new Function('module', 'exports', 'require', output.outputFiles[0].text)(module, module.exports, require);
const engine = module.exports;
const game = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const deck = new Map(Object.entries(game.deck_map).map(([id, face]) => [Number(id), face]));
const score = engine.computeBaseScore(game.hand_tiles, deck, game.tile_score_map);
assert(score > 0n);
const rules = game.effect_list.map(item => engine.resolveAmuletRule(item));
assert.equal(rules.length, game.effect_list.length);
const result = engine.calculateCurrentPoint(score, 100n, game.level, rules);
assert(result.finalPoint >= 0n);
const growth = engine.resolveAmuletRule({id:2291, uid:9, volume:1, tags:[], store:['230','0']});
assert.equal(growth.dataRaw, '230');
assert.equal(engine.parseTargetPointValue(game.target_point), 20000n);
console.log('QYZZ score calculator: state, base score, growth and target checks passed');
